In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]
ar=np.array(l)
ar

array([1, 2, 3, 4])

In [3]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [4]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [9]:
np.asarray(l)

array([1, 2, 3, 4])

In [5]:
b=np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [6]:
type(b)

numpy.matrix

In [10]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [12]:
type(np.asanyarray(b))

numpy.matrix

In [13]:
a =np.array(l)

In [14]:
a

array([1, 2, 3, 4])

In [15]:
c=a

In [16]:
c

array([1, 2, 3, 4])

In [17]:
c[0] = 100

In [18]:
c

array([100,   2,   3,   4])

In [19]:
a

array([100,   2,   3,   4])

In [20]:
d = np.copy(a)

In [21]:
d

array([100,   2,   3,   4])

In [22]:
d[0]=400

In [23]:
d

array([400,   2,   3,   4])

In [24]:
a

array([100,   2,   3,   4])

In [26]:
np.fromfunction(lambda i,j: i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
iterable=(i*i for i in range(5))
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [46]:
np.fromstring('123 456',sep =' ')

array([123., 456.])

In [47]:
ar =np.array(l)

In [48]:
ar

array([1, 2, 3, 4])

In [49]:
ar.ndim

1

In [130]:
ar1 = np.array([[1,2,3,4],[5,6,7,8]])

In [55]:
ar1.ndim

2

In [56]:
ar1.size

8

In [57]:
ar1.shape

(2, 4)

In [58]:
ar.dtype

dtype('int32')

In [59]:
ar1.dtype

dtype('int32')

In [60]:
ar2 =np.array([[12.4,2,3],[4,5,6]])

In [61]:
ar2

array([[12.4,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [62]:
ar2.dtype

dtype('float64')

In [64]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [65]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [66]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [67]:
np.arange(1,25,5)

array([ 1,  6, 11, 16, 21])

In [91]:
np.linspace(0,100,21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [92]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [96]:
x =np.ones((2,3,2))

In [97]:
x

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [98]:
x+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [99]:
x*2

array([[[2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.]]])

In [108]:
np.empty((3,2))

array([[12.4,  2. ],
       [ 3. ,  4. ],
       [ 5. ,  6. ]])

In [109]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [110]:
np.logspace(2,5,10,base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [117]:

arr = np.random.randn(3,4)

In [118]:
arr

array([[-0.49406587,  0.49581656,  1.55181276, -0.73607649],
       [ 0.13207215,  1.66894069,  0.23192394,  0.45235278],
       [-0.55511065,  0.79165644,  0.89139921, -0.50996636]])

In [119]:
import pandas as pd

In [120]:
pd.DataFrame(arr)

0         1         2         3
0 -0.494066  0.495817  1.551813 -0.736076
1  0.132072  1.668941  0.231924  0.452353
2 -0.555111  0.791656  0.891399 -0.509966

In [121]:
np.random.rand(2,3)

array([[0.64374099, 0.49510442, 0.93871993],
       [0.32630481, 0.40147574, 0.08527346]])

In [122]:
np.random.randint(1,110,(3,4))

array([[62, 81, 77, 43],
       [15, 39, 30, 21],
       [79, 52, 73, 91]])

In [123]:
#randomly generates numbers and convert it in to the dataframe 

In [124]:
pd.DataFrame(np.random.randint(1,110,(100,200))).to_csv('My_random_DataFrame')

In [125]:
arr

array([[-0.49406587,  0.49581656,  1.55181276, -0.73607649],
       [ 0.13207215,  1.66894069,  0.23192394,  0.45235278],
       [-0.55511065,  0.79165644,  0.89139921, -0.50996636]])

In [129]:
arr.reshape(6,-1)

array([[-0.49406587,  0.49581656],
       [ 1.55181276, -0.73607649],
       [ 0.13207215,  1.66894069],
       [ 0.23192394,  0.45235278],
       [-0.55511065,  0.79165644],
       [ 0.89139921, -0.50996636]])